In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()

for candidate in [PROJECT_ROOT, PROJECT_ROOT.parent]:
    if (candidate / "pyproject.toml").exists():
        PROJECT_ROOT = candidate
        break

SRC_DIR = PROJECT_ROOT / "src"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

if SRC_DIR.exists() and str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
EVAL_DIR = DATA_DIR / "evaluation"
PROCESSED_DIR = DATA_DIR / "processed"

print(f"Project root: {PROJECT_ROOT}")
print(f"Evaluation dir: {EVAL_DIR}")

Project root: /Users/rodrigue.lawson/VSCode Projects/lexcare-ai
Evaluation dir: /Users/rodrigue.lawson/VSCode Projects/lexcare-ai/data/evaluation

In [2]:
import json
from pathlib import Path

import pandas as pd

from app.services.rag_service import RAGService
from app.services.retriever_service import RetrieverService
from app.services.vectorstore_service import VectorStoreService
from app.services.embedding_service import EmbeddingService

In [3]:
test_set_path = EVAL_DIR / "test_questions.json"

with test_set_path.open("r", encoding="utf-8") as f:
    test_set = json.load(f)

test_set

[{'id': 'q1',
  'question': 'Was ist Pflegegrad 3?',
  'expected_answer': 'Schwere Beeinträchtigungen der Selbständigkeit oder der Fähigkeiten; Zuordnung bei 47,5 bis unter 70 Gesamtpunkten.',
  'expected_topics': ['pflegeversicherung', 'pflegegrad'],
  'expected_sources': ['SGB_11.pdf']},
 {'id': 'q2',
  'question': 'Wer hat Anspruch auf Pflegegeld?',
  'expected_answer': 'Versicherte mit Pflegegrad 2 bis 5 bei häuslicher Pflege durch geeignete Pflegepersonen.',
  'expected_topics': ['pflegegeld', 'pflegeversicherung'],
  'expected_sources': ['SGB_11.pdf']},
 {'id': 'q3',
  'question': 'Wie hoch ist der Entlastungsbetrag?',
  'expected_answer': 'Der Entlastungsbetrag beträgt monatlich 125 Euro.',
  'expected_topics': ['entlastungsbetrag', 'pflegeleistungen'],
  'expected_sources': ['SGB_11.pdf']},
 {'id': 'q4',
  'question': 'Was regelt das PUEG?',
  'expected_answer': 'Änderungen zur Unterstützung und Entlastung in der Pflege, inklusive Leistungsanpassungen und Strukturreformen.',
  'expected_topics': ['pflegereform', 'pueg'],
  'expected_sources': ['PUEG_RefE_Pflegereform_bf.pdf']},
 {'id': 'q5',
  'question': 'Welche Leistungen sind in der gesetzlichen Krankenversicherung geregelt?',
  'expected_answer': 'Leistungen der gesetzlichen Krankenversicherung, unter anderem Krankenbehandlung, Arznei- und Heilmittel sowie weitere Leistungsansprüche.',
  'expected_topics': ['krankenversicherung', 'leistungen'],
  'expected_sources': ['SGB_5.pdf']}]

In [4]:
vectorstore_service = VectorStoreService()
retriever = RetrieverService(vectorstore_service)
rag = RAGService(retriever_service=retriever)

/Users/rodrigue.lawson/VSCode Projects/lexcare-ai/app/services/vectorstore_service.py:26: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the `langchain-chroma package and should be used instead. To use it run `pip install -U `langchain-chroma` and import as `from `langchain_chroma import Chroma``.
  self._store = Chroma(

In [5]:
records = []

for item in test_set:
    question = item["question"]
    retrieved = retriever.retrieve(question, top_k=5)

    records.append(
        {
            "id": item["id"],
            "question": question,
            "expected_answer": item["expected_answer"],
            "expected_sources": ", ".join(item["expected_sources"]),
            "retrieved_sources": ", ".join(
                sorted({chunk.metadata.extra.get("filename", Path(chunk.source_path).name) for chunk in retrieved})
            ),
            "retrieved_chunk_ids": ", ".join(chunk.chunk_id for chunk in retrieved),
            "retrieved_preview": retrieved[0].text[:400] if retrieved else "",
            "hit": any(
                Path(chunk.source_path).name in item["expected_sources"]
                for chunk in retrieved
            ),
        }
    )

df_eval = pd.DataFrame(records)
df_eval

,id,question,expected_answer,expected_sources,retrieved_sources,retrieved_chunk_ids,retrieved_preview,hit
0,q1,Was ist Pflegegrad 3?,Schwere Beeinträchtigungen der Selbständigkeit...,SGB_11.pdf,SGB_11.pdf,0b859b80-8f28-4172-978c-feb589417aa0-chunk-088...,ach\nMaßgabe von Satz 3 einem Pflegegrad zugeo...,True
1,q2,Wer hat Anspruch auf Pflegegeld?,Versicherte mit Pflegegrad 2 bis 5 bei häuslic...,SGB_11.pdf,"SGB_11.pdf, SGB_5.pdf",0b859b80-8f28-4172-978c-feb589417aa0-chunk-024...,ige der Pflegegrade 2 bis 5 können anstelle de...,True
2,q3,Wie hoch ist der Entlastungsbetrag?,Der Entlastungsbetrag beträgt monatlich 125 Euro.,SGB_11.pdf,"PUEG_RefE_Pflegereform_bf.pdf, SGB_11.pdf",0b859b80-8f28-4172-978c-feb589417aa0-chunk-088...,"nuar 2017 zustehen, nicht um jeweils mindesten...",True
3,q4,Was regelt das PUEG?,Änderungen zur Unterstützung und Entlastung in...,PUEG_RefE_Pflegereform_bf.pdf,"PUEG_RefE_Pflegereform_bf.pdf, SGB_11.pdf, SGB...",a045aad7-0d31-46df-8243-289cb921641a-chunk-000...,Referentenentwurf\ndes Bundesministeriums für ...,True
4,q5,Welche Leistungen sind in der gesetzlichen Kra...,Leistungen der gesetzlichen Krankenversicherun...,SGB_5.pdf,SGB_5.pdf,676aebc2-2db0-46c9-9086-72ed95b36887-chunk-001...,"durch Aufklärung, Beratung und Leistungen zu\n...",True

In [6]:
df_eval[[
    "id",
    "question",
    "expected_sources",
    "retrieved_sources",
    "hit",
]]

,id,question,expected_sources,retrieved_sources,hit
0,q1,Was ist Pflegegrad 3?,SGB_11.pdf,SGB_11.pdf,True
1,q2,Wer hat Anspruch auf Pflegegeld?,SGB_11.pdf,"SGB_11.pdf, SGB_5.pdf",True
2,q3,Wie hoch ist der Entlastungsbetrag?,SGB_11.pdf,"PUEG_RefE_Pflegereform_bf.pdf, SGB_11.pdf",True
3,q4,Was regelt das PUEG?,PUEG_RefE_Pflegereform_bf.pdf,"PUEG_RefE_Pflegereform_bf.pdf, SGB_11.pdf, SGB...",True
4,q5,Welche Leistungen sind in der gesetzlichen Kra...,SGB_5.pdf,SGB_5.pdf,True

In [7]:
hit_rate = df_eval["hit"].mean()
print(f"Hit rate@5: {hit_rate:.2%}")

Hit rate@5: 100.00%

In [8]:
for item in test_set:
    result = rag.answer(item["question"], top_k=5)
    print("=" * 100)
    print(item["question"])
    print(result.answer)
    print("Sources:")
    for src in result.sources:
        print(src)
    print()

====================================================================================================
Was ist Pflegegrad 3?
Pflegegrad 3 bedeutet schwere Beeinträchtigungen der Selbständigkeit oder der Fähigkeiten. Er wird bei Gesamtpunkten von 47,5 bis unter 70 vergeben. (Quelle: § 15 Absatz 3, Begutachtungsinstrument – 0b859b80-8f28-4172-978c-feb589417aa0, chunk 131)
Sources:
document_id='0b859b80-8f28-4172-978c-feb589417aa0' chunk_id='0b859b80-8f28-4172-978c-feb589417aa0-chunk-0880' source='gesetze-im-internet' score=None
document_id='0b859b80-8f28-4172-978c-feb589417aa0' chunk_id='0b859b80-8f28-4172-978c-feb589417aa0-chunk-0130' source='gesetze-im-internet' score=None
document_id='0b859b80-8f28-4172-978c-feb589417aa0' chunk_id='0b859b80-8f28-4172-978c-feb589417aa0-chunk-0307' source='gesetze-im-internet' score=None
document_id='0b859b80-8f28-4172-978c-feb589417aa0' chunk_id='0b859b80-8f28-4172-978c-feb589417aa0-chunk-0131' source='gesetze-im-internet' score=None
document_id='0b859b80-8f28-4172-978c-feb589417aa0' chunk_id='0b859b80-8f28-4172-978c-feb589417aa0-chunk-0127' source='gesetze-im-internet' score=None

====================================================================================================
Wer hat Anspruch auf Pflegegeld?
Anspruch auf Pflegegeld haben Pflegebedürftige der Pflegegrade 2 bis 5, die anstelle der häuslichen Pflegehilfe Pflegegeld beantragen und dabei sicherstellen, dass sie die erforderlichen körperbezogenen Pflegemaßnahmen, pflegerische Betreuungsmaßnahmen sowie Hilfen bei der Haushaltsführung selbst in geeignetem Umfang sicherstellen.

Beitragsbeträge (monatlich):
- Pflegegrad 2: 347 Euro
- Pflegegrad 3: 599 Euro
- Pflegegrad 4: 800 Euro
- Pflegegrad 5: 990 Euro

Hinweis: Bei anteiligem Anspruch wird der Betrag entsprechend gekürzt. Die Hälfte des bisherigen Pflegegeldes wird während Kurzzeitpflege (§ 42) und Verhinderungspflege (§ 39) bis zu acht Wochen je Kalenderjahr fortgewährt. (Absatz 1–2)
Sources:
document_id='0b859b80-8f28-4172-978c-feb589417aa0' chunk_id='0b859b80-8f28-4172-978c-feb589417aa0-chunk-0245' source='gesetze-im-internet' score=None
document_id='0b859b80-8f28-4172-978c-feb589417aa0' chunk_id='0b859b80-8f28-4172-978c-feb589417aa0-chunk-0246' source='gesetze-im-internet' score=None
document_id='0b859b80-8f28-4172-978c-feb589417aa0' chunk_id='0b859b80-8f28-4172-978c-feb589417aa0-chunk-0027' source='gesetze-im-internet' score=None
document_id='0b859b80-8f28-4172-978c-feb589417aa0' chunk_id='0b859b80-8f28-4172-978c-feb589417aa0-chunk-0237' source='gesetze-im-internet' score=None
document_id='676aebc2-2db0-46c9-9086-72ed95b36887' chunk_id='676aebc2-2db0-46c9-9086-72ed95b36887-chunk-0447' source='gesetze-im-internet' score=None

====================================================================================================
Wie hoch ist der Entlastungsbetrag?
Der Entlastungsbetrag beträgt bis zu 131 Euro monatlich (Pflegebedürftige in häuslicher Pflege; § 45b Absatz 1 SGB XI). Referenz: 0b859b80-...-chunk-0335.
Sources:
document_id='0b859b80-8f28-4172-978c-feb589417aa0' chunk_id='0b859b80-8f28-4172-978c-feb589417aa0-chunk-0886' source='gesetze-im-internet' score=None
document_id='a045aad7-0d31-46df-8243-289cb921641a' chunk_id='a045aad7-0d31-46df-8243-289cb921641a-chunk-0017' source='gesetze-im-internet' score=None
document_id='d335538b-74d9-4f6f-83ca-cebf17768798' chunk_id='d335538b-74d9-4f6f-83ca-cebf17768798-chunk-0017' source='gesetze-im-internet' score=None
document_id='0b859b80-8f28-4172-978c-feb589417aa0' chunk_id='0b859b80-8f28-4172-978c-feb589417aa0-chunk-0335' source='gesetze-im-internet' score=None
document_id='d335538b-74d9-4f6f-83ca-cebf17768798' chunk_id='d335538b-74d9-4f6f-83ca-cebf17768798-chunk-0208' source='gesetze-im-internet' score=None

====================================================================================================
Was regelt das PUEG?
Das PUEG (Pflegeunterstützungs- und -entlastungsgesetz) ist der Referentenentwurf eines Gesetzes zur Unterstützung und Entlastung in der Pflege. Es regelt vor allem:

- automatische, regelhafte Anpassungen der Geld- und Sachleistungsbeträge in der Pflegeversicherung (jeweils vorgesehen für 2025 und 2028).
- Stärkung der häuslichen Pflege und Entlastung pflegebedürftiger Menschen, ihrer Angehörigen und anderer Pflegepersonen.
- Verbesserungen der Arbeitsbedingungen für professionell Pflegende.
- Nutzung der Digitalisierung für Pflegebedürftige und Pflegende; Förderung von Innovationen; mehr Unterstützung insbesondere für häuslich gepflegte Menschen.
- Fördervolumen für Unterstützungsmaßnahmen und -strukturen vor Ort und im Quartier (bis zu 25 Millionen Euro für 2024–2028).
- Änderungen am Fünften Buch Sozialgesetzbuch (SGB V) in Artikel 1.

Quellen/Verweise: Referentenentwurf des BMG zum PUEG, A. Problem und Ziel; Fördervolumen (2024–2028); Änderung des SGB V (Artikel 1).
Sources:
document_id='a045aad7-0d31-46df-8243-289cb921641a' chunk_id='a045aad7-0d31-46df-8243-289cb921641a-chunk-0000' source='gesetze-im-internet' score=None
document_id='d335538b-74d9-4f6f-83ca-cebf17768798' chunk_id='d335538b-74d9-4f6f-83ca-cebf17768798-chunk-0000' source='gesetze-im-internet' score=None
document_id='d335538b-74d9-4f6f-83ca-cebf17768798' chunk_id='d335538b-74d9-4f6f-83ca-cebf17768798-chunk-0026' source='gesetze-im-internet' score=None
document_id='0b859b80-8f28-4172-978c-feb589417aa0' chunk_id='0b859b80-8f28-4172-978c-feb589417aa0-chunk-0830' source='gesetze-im-internet' score=None
document_id='676aebc2-2db0-46c9-9086-72ed95b36887' chunk_id='676aebc2-2db0-46c9-9086-72ed95b36887-chunk-3240' source='gesetze-im-internet' score=None

====================================================================================================
Welche Leistungen sind in der gesetzlichen Krankenversicherung geregelt?
Kurz gesagt: In der gesetzlichen Krankenversicherung (GKV) sind die Leistungen in § 11 Leistungsarten des SGB V geregelt.

Nach § 11 Absatz 1 stehen Versicherte Leistungen zu in den folgenden Kategorien:
- Schwangerschaft und Mutterschaft (§§ 24c–24i)
- Verhütung von Krankheiten bzw. deren Verschlimmerung sowie Empfängnisverhütung, Sterilisation und Schwangerschaftsabbruch (§§ 20–24b)
- zur Erfassung von Gesundheit‑srisiken und Früherkennung von Krankheiten (§§ 25–26)
- zur Behandlung einer Krankheit (§§ 27–52)
- das Persönliche Budget nach § 29 des Neunten Buches

Nach § 11 Absatz 2 bestehen darüber hinaus Ansprüche auf medizinische Rehabilitation sowie auf unterhaltssichernde und andere ergänzende Leistungen, die notwendig sind, um eine Behinderung oder Pflegebedürftigkeit abzuwenden bzw. zu mildern. Zudem werden Leistungen der aktivierenden Pflege nach Eintritt von Pflegebedürftigkeit von den Pflegekassen erbracht.

Zusätzliche Regelungen finden sich z. B. in:
- § 23 Medizinische Vorsorgeleistungen (Anspruch auf ärztliche Behandlung und Versorgung mit Arznei-, Verband-, Heil- und Hilfsmitteln, wenn notwendig)
- §§ 2a/2b (besondere Belange behinderter/chronisch kranker Menschen sowie geschlechts- und altersspezifische Besonderheiten)

Quellen: § 11 Leistungsarten (chunk 0072), § 23 Medizinische Vorsorgeleistungen (chunk 170), §§ 2a/2b (chunk 0016).
Sources:
document_id='676aebc2-2db0-46c9-9086-72ed95b36887' chunk_id='676aebc2-2db0-46c9-9086-72ed95b36887-chunk-0013' source='gesetze-im-internet' score=None
document_id='676aebc2-2db0-46c9-9086-72ed95b36887' chunk_id='676aebc2-2db0-46c9-9086-72ed95b36887-chunk-0072' source='gesetze-im-internet' score=None
document_id='676aebc2-2db0-46c9-9086-72ed95b36887' chunk_id='676aebc2-2db0-46c9-9086-72ed95b36887-chunk-0016' source='gesetze-im-internet' score=None
document_id='676aebc2-2db0-46c9-9086-72ed95b36887' chunk_id='676aebc2-2db0-46c9-9086-72ed95b36887-chunk-0170' source='gesetze-im-internet' score=None
document_id='676aebc2-2db0-46c9-9086-72ed95b36887' chunk_id='676aebc2-2db0-46c9-9086-72ed95b36887-chunk-2652' source='gesetze-im-internet' score=None

In [9]:
output_path = PROCESSED_DIR / "retrieval_evaluation_results.csv"
output_path.parent.mkdir(parents=True, exist_ok=True)
df_eval.to_csv(output_path, index=False)

print(f"Saved to: {output_path}")

Saved to: /Users/rodrigue.lawson/VSCode Projects/lexcare-ai/data/processed/retrieval_evaluation_results.csv